### ISSUE TITLE
Negative adjustment means Left and Right?

### ISSUE THREAD

**Issue by paulbuzzby** [ukmars/ukmarsbot-mazerunner#13]
I've just been looking through the code and have noticed a possible inconsistency.

In sensors.cpp 

the **calculate_steering_adjustment** method comments states
`* @param error calculated from wall sensors, Negative if too far right`

But for **update_wall_sensors** the method comments state
`* @return robot cross-track-error. Too far left is negative.`

I've not gone through the code enough to verify that the code is doing this so it might just be a mistake with the comments and while it shouldn't break anything, it is slightly confusing if different methods use different logic for left and right corrections.

**Comment by micromouseonline** [comment]
Thank you for noticing and bringing this to my attention.

i have edited the calculate_steering_adjustment comment to make it consistent
