### ISSUE TITLE
Message to Peter Harrison

### ISSUE THREAD

**Issue by Cognisant1** [ukmars/ukmarsbot-mazerunner#5]
I don’t know how to contact Peter directly, but just wanted to say a huge thank you for enabling me to enjoy hours building, programming and running ukmarsbot!
I’m 82 years old but now have a fully functioning mouse which can create the optimal diagonal path through a 6x6 maze.

**Comment by derekchall** [comment]
That’s fantastic. That will be the first diagonal running UKMarsBot, will we be seeing you at any of the contests in the UK this year?
Peter should see your message.
Derek Hall
[www.ukmars.org](url)
[www.micromouse.me.uk](url)

**Comment by micromouseonline** [comment]
Thank you.  You are too kind. 

I look forward to seeing your robot run. It would be great if you could get to one of the events.

**Comment by Cognisant1** [comment]
Sent from my iPhone
Not at all Peter. Here is a video of the mouse in action. The diagonal is not steered at the moment so just depends on accuracy of the 45 degree turns. But it works!! I’ve designed a two front sensor front end and will try that for steering on the diagonals. Adrian

**Comment by Cognisant1** [comment]
Hi Peter. Can you get the video on this GitHub email? Adrian

**Comment by Cognisant1** [comment]
﻿
﻿
﻿Dear Peter 

I have now fitted a new “front end” with two forwards facing LEDs and new software for steering on diagonals. Here is a video (which I hope you can receive on this email address) showing an extended search run then a long diagonal speed run. 

Best wishes

Adrian

**Comment by Cognisant1** [comment]
﻿
﻿
﻿
﻿Dear Peter 

I have now fitted a new “front end” with two forwards facing LEDs and new software for steering on diagonals. Here is a video (which I hope you can receive on this email address) showing an extended search run then a long diagonal speed run. 

Best wishes

Adrian

**Comment by Cognisant1** [comment]
﻿
Hi Peter and Derek 

I don’t think you can see the videos on the GitHub site. Here is the diagonal run on YouTube. 

Best wishes

Adrian

https://youtu.be/smgfeDTj2T4


Sent from my iPhone

**Comment by derekchall** [comment]
Thanks that looks really good

**Comment by micromouseonline** [comment]
Excellent! Really impressive.

**Comment by micromouseonline** [comment]
Thank you for your comments. I am closing this issue because it does not require action for the repository.
